name: remla2025-team19
services:
    app:
        image: ghcr.io/remla2025-team19/app-service:0.0.14
        ports:
            - '8080:8080'
        depends_on:
            - model
        environment:
            - MODEL_SERVICE_URL=http://model:8080
    model:
        image: ghcr.io/remla2025-team19/model-service:0.0.5
        ports:
            - '3000:8080'
        environment:
            - MODEL_CACHE_DIR=/models_cache
        volumes:
            - ./model_cache_local:/models_cache
