name: remla2025-team19
services:
    app:
        image: ghcr.io/remla2025-team19/app-service:0.0.15
        ports:
            - '8080:8080'
        depends_on:
            - model
        environment:
            - MODEL_SERVICE_URL=http://model:8080
        restart: unless-stopped
    model:
        #TODO: update to the latest version when everything in model-service is merged
        image: ghcr.io/remla2025-team19/model-service:0.0.7
        environment:
            - MODEL_CACHE_DIR=/app/models_cache
            - MODEL_VERSION=v1.0.11
            - MODEL_SERVICE_HOST=0.0.0.0
            - MODEL_SERVICE_PORT=8080
        volumes:
            - ./model_cache_local:/app/models_cache
        restart: unless-stopped
        healthcheck:
            test:
                [
                    'CMD',
                    'sh',
                    '-c',
                    'curl -f http://localhost:$MODEL_SERVICE_PORT/health',
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
