apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-service
          image: ghcr.io/remla2025-team19/app-service:0.0.14
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MODEL_API_URL
            # fake variables
            - name: APP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
            - name: APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: API_KEY
            - name: APP_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: DB_PASSWORD
          # Placeholder, added because "One or more containers do not have resources - this can cause noisy neighbor issues" lint error
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOG_LEVEL: "info"
  MODEL_API_URL: "http://model:5001"
  DB_USER: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
type: Opaque
data:
  API_KEY: "c2stdjEta2pkZmxrYWhmbHNkYWl1eWhjb3V3aWhxZW91cmg="
  DB_PASSWORD: "cGFzc3dvcmQ="
