apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
  labels:
    app: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model-service
          image: ghcr.io/remla2025-team19/model-service:0.0.5
          ports:
            - containerPort: 5001
          env:
            - name: MODEL_VERSION
              valueFrom:
                configMapKeyRef:
                  name: model-config
                  key: MODEL_VERSION
            - name: MODEL_ARTIFACT_URL
              valueFrom:
                configMapKeyRef:
                  name: model-config
                  key: MODEL_ARTIFACT_URL
            - name: PREDICTION_THRESHOLD
              valueFrom:
                configMapKeyRef:
                  name: model-config
                  key: PREDICTION_THRESHOLD
            - name: MODEL_CACHE_DIR
              value: "/models_cache"
          volumeMounts:
            - name: model-cache-volume
              mountPath: /models_cache
          # Placeholder, added because "One or more containers do not have resources - this can cause noisy neighbor issues" lint error
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: model-cache-volume
          hostPath:
            path: /mnt/shared/model_cache
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: model
  labels:
    app: model
spec:
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-config
data:
  # Undecided how to approach this, version tag seems more maintainable maybe
  MODEL_VERSION: "1.0.11"
  MODEL_ARTIFACT_URL: "https://github.com/remla2025-team19/model-training/releases/download/v1.0.11/sentiment_model_v1.0.11.pkl"
  PREDICTION_THRESHOLD: "0.75" # random variable
