- name: "Step 5.1: Disable swap (runtime)"
  ansible.builtin.shell: swapoff -a

- name: "Step 5.2: Remove swap entry from /etc/fstab (persist on reboot)"
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+)'
    state: absent