

- name: Download Kubernetes signing key (ASCII)
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    state: present



- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /
    filename: kubernetes
    state: present

- name: Refresh APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600