- name: "Step 10.1: Set version facts"
  set_fact:
    k8s_ver: "1.32.4-1.1"              

- name: "Step 10.2: Install containerd + runc"
  apt:
    name:
      - containerd
      - runc
    state: present
    update_cache: yes
  notify: restart containerd

- name: "Step 10.3 Enable and start containerd"
  systemd:
    name: containerd
    enabled: yes
    state: started

- name: "Step 10.4: Install kubelet, kubeadm, kubectl"
  apt:
    name:
      - "kubelet={{ k8s_ver }}"
      - "kubeadm={{ k8s_ver }}"
      - "kubectl={{ k8s_ver }}"
    state: present
    update_cache: yes

- name: "Step 10.5: Hold Kubernetes packages at {{ k8s_ver }}"
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl