- name: Create host kubeconfig directory
  file:
    path: "{{ playbook_dir }}/kubeconfig"
    state: directory
    mode: '0755'
  run_once: true

- name: Fetch admin.conf to host
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ playbook_dir }}/kubeconfig/config"
    flat: yes
  run_once: true

- name: Add kubeconfig/ to .gitignore on host
  lineinfile:
    path: "{{ playbook_dir }}/../.gitignore"
    line: "kubeconfig/"
    create: yes
  run_once: true
  delegate_to: localhost
  connection: local
  become: false
