- name: "Step 15.1: Download Flannel"
  get_url:
    url: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
    dest: /tmp/kube-flannel.yml
    mode: '0644'
  run_once: true

- name: "Step 15.2: Add --iface=eth1 to the Flannel DaemonSet args"
  lineinfile:
    path: /tmp/kube-flannel.yml
    regexp: '(\s+)- --kube-subnet-mgr'
    line: '\1- --kube-subnet-mgr\n\1- --iface=eth1'
    backrefs: yes
  run_once: true

- name: "Step 15.3: Apply Flannel Pod network manifest"
  shell: |
    kubectl apply \
      --kubeconfig=/etc/kubernetes/admin.conf \
      --validate=false \
      -f /tmp/kube-flannel.yml
  run_once: true

