
- name: Download Helm GPG key (ASCII)
  apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    state: present
    update_cache: yes

- name: Add Helm APT repository
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    filename: helm
    state: present

- name: Install Helm package
  apt:
    name: helm
    state: present
    update_cache: yes
