- name: "Step 18.1: Check if cluster is initialized"
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf
  delegate_to: ctrl
  changed_when: false

- name: "Step 18.2: Generate join command on controller"
  shell: kubeadm token create --print-join-command
  register: join_command
  delegate_to: ctrl
  when: admin_conf.stat.exists
  changed_when: "'New token created' in join_command.stdout"

- name: "Step 18.3: Set join command as a global fact"
  set_fact:
    join_command: "{{ join_command.stdout }}"
  delegate_to: ctrl
  delegate_facts: true
  run_once: true