- import_tasks: 04-ssh-key-setup.yml
- import_tasks: 05-disable-swap.yml
- import_tasks: 06-load-kernel.yml
- import_tasks: 07-ip-forward-bridge-nf.yml
- import_tasks: 08-manage-hosts.yml
- import_tasks: 09-add-kube-repo.yml
- import_tasks: 10-k8s-tools.yml
- import_tasks: 11-configure-containerd.yml
- import_tasks: 12-start-kubelet.yml

- name: Initialize control plane
  include_tasks: 13-init-cluster.yml
  when: inventory_hostname == 'ctrl' # only run on ctrl VM

- name: Setup kubectl for host
  include_tasks: 14-setup-kubectl.yml
  when: inventory_hostname == 'ctrl' # only run on ctrl VM

- name: Create Pod network
  include_tasks: 15-create-pod-network.yml
  when: inventory_hostname == 'ctrl'

- name: Install Helm
  include_tasks: 16-install-helm.yml
  when: inventory_hostname == 'ctrl'

- name: Install Helm Diff plugin
  include_tasks: 17-helm-plugin.yml
  when: inventory_hostname == 'ctrl'

- name: Create join command
  include_tasks: 18-join-command.yml
  when: inventory_hostname == 'node-1,node-2' #

- name: Join worker nodes to the cluster
  include_tasks: 19-join-worker.yml
  when: inventory_hostname == 'node-1,node-2' # only run on node-1 and node-2 VMs
  vars:
    join_command: "{{ hostvars['ctrl'].join_command }}"